    for i in range(6):
        plt.figure()
        plt.subplot(211)
        plt.plot(PPGdata[i])
        plt.title('PPG '+Condition[i])
        plt.xlim([0, len(PPGdata[i])])
        plt.plot(Maxpos1[i], Maxpeak1[i], 'ro')
        plt.plot(Minpos1[i], Minpeak1[i], 'bo')
        plt.subplot(212)
        plt.plot(EDAdata[i], 'g')
        plt.title('EDA '+Condition[i])
        plt.xlim([0, len(EDAdata[i])])
        plt.plot(maxpos1[i], maxpeak1[i], 'ro')
        plt.plot(minpos1[i], minpeak1[i], 'bo')
    plt.show()